### PR TITLE
Update firebase commands - update pods and swift files to latest version #39

### PR DESCRIPTION
**Pull request by welljsjs**
Updated to match the current Firebase framework and its documentation.

### CODE REVIEW

**Comment by welljsjs** [comment]
@Lino17 

> Accaunt welles Fargo benk scaduto

> Uw

Please translate your comments into English. Not the whole world can understand Italian.

**Comment by gurpalrajput** [comment]
Can you update this for swift 4.0

**Comment by welljsjs** [comment]
@GurpalRajput Who? Me? And what are you talking about? The changes I made to the QuickChat folder are all in Swift 4.x. If you're experiencing issues with the Firebase Framework, you have to update the pods.

**Comment by gurpalrajput** [comment]
screen shot 2018-06-07 at 7 40 47 pm
thats what i am getting in error. please help me out here

**Comment by welljsjs** [comment]
[I recommend starting here.](https://cocoapods.org/index#get_started) Did you try updating your pods or repos? How is your question related to this specific issue? @GurpalRajput Also have a look here https://github.com/google/santa/issues/64

**Pull request closed without merging**
